baseURL = "https://yyjhao.com/"
languageCode = "en-us"
title = "yyjhao"
theme = "hugo-notepadio"
sectionPagesMenu = "main"
disqusShortname = "yyjhao"
copyright = "©2021 Yujian Yao"
googleAnalytics = "UA-192108237-1"

[Author]
    name = "Yujian Yao"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true

[params]
  style = "light"
  dateFormat = "Monday, January 2, 2006"
  fullRss = false
  css = ["css/override.css"]
  
  [params.comments]
    enable = true

[[params.nav.custom]]
  title = "RSS"
  url = "/index.xml"

[[params.nav.custom]]
  title = "Github"
  url = "https://github.com/yyjhao"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"